# Generated by Django 3.1.7 on 2021-03-06 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashflow',
            name='priceCredit',
            field=models.FloatField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='priceDebit',
            field=models.FloatField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='priceSaldo',
            field=models.FloatField(default=0, max_length=100),
        ),
    ]
