# Generated by Django 3.1.7 on 2021-03-06 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_auto_20210306_0441'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cashflow',
            old_name='priceCredit',
            new_name='Saldo',
        ),
        migrations.RenameField(
            model_name='cashflow',
            old_name='priceDebit',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='cashflow',
            name='priceSaldo',
        ),
    ]
