# Generated by Django 3.1.7 on 2021-03-06 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_auto_20210306_1011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cashflow',
            old_name='Saldo',
            new_name='saldo',
        ),
    ]
