# Generated by Django 3.1.7 on 2021-03-10 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_auto_20210309_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflow',
            name='note',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
