# Generated by Django 3.1.7 on 2021-03-10 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_cashflow_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashflow',
            name='note',
        ),
    ]
